import type { AppProps } from 'next/app';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Provider } from 'react-redux';
import { Bounce, ToastContainer } from 'react-toastify';

import { useAuth } from '@/hooks/useAuth';
import { ChatsProvider } from '@/hooks/useChat';
import Layout from '@/layout';
import AdminLayout from '@/layout/AdminLayout';
import { store } from '@/redux';
import ThemeConfig from '@/theme';

import '@/theme/styles/styles.scss';

function AppContent({ Component, pageProps }: AppProps) {
    const router = useRouter();
    
    // Загружаем данные пользователя при инициализации приложения
    // Этот хук должен быть внутри Provider, поэтому вызываем его здесь
    useAuth();

    // Если путь начинается с "/admin", то используем AdminLayout
    const isAdmin = router.pathname.startsWith('/admin');
    const ActiveLayout = isAdmin ? AdminLayout : Layout;

    return (
        <>
            <ToastContainer
                position="top-center"
                autoClose={3000}
                hideProgressBar={true}
                closeOnClick={false}
                pauseOnFocusLoss={false}
                pauseOnHover={false}
                draggable={false}
                rtl={false}
                theme="colored"
                transition={Bounce}
                enableMultiContainer={false}
                newestOnTop={true}
                limit={1}
            />
            <Head>
                <title>Al Salam Technology</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ThemeConfig>
                <ActiveLayout>
                    <ChatsProvider>
                        <Component {...pageProps} />
                    </ChatsProvider>
                </ActiveLayout>
            </ThemeConfig>
        </>
    );
}

export default function App(props: AppProps) {
    return (
        <Provider store={store}>
            <AppContent {...props} />
        </Provider>
    );
}
